packages:
  - apps/*
  - packages/*
allowBuilds:
  "@ffmpeg-installer/darwin-arm64": true
  "@livekit/local-inference": true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
